//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArbolesPlantas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuesto
    {
        public int Id { get; set; }
        public int id_factura { get; set; }
        public System.DateTime fechaAlta { get; set; }
        public string areaSolicita { get; set; }
        public float total { get; set; }
        public float presupuestoInicial { get; set; }
        public float presupuestoActual { get; set; }
        public int status { get; set; }
    
        public virtual Factura Factura { get; set; }
    }
}
